// ─── Educational Analysis Types ─────────────────────────────────────
// Generated by client LLM (Claude Code, Cursor etc.) during MCP sync.
// Used to enrich learning curriculum generation with deep project insights.

export type AppType =
  | "saas"
  | "ecommerce"
  | "social"
  | "blog"
  | "dashboard"
  | "game"
  | "tool"
  | "portfolio"
  | "api_service"
  | "other";

export type DifficultyLevel = "beginner" | "intermediate" | "advanced";

export type FileDifficulty = "beginner" | "intermediate" | "advanced";

export type QualityInsightSeverity = "info" | "warning" | "important";

// ─── Project Overview ───────────────────────────────────────────────

export interface TechMetaphor {
  tech_name: string;
  metaphor: string; // e.g., "Next.js → 레스토랑 주방장"
}

export interface ProjectOverview {
  one_liner: string;
  app_type: AppType;
  target_users: string;
  core_features: string[];
  tech_stack_metaphors: TechMetaphor[];
}

// ─── User Flows ─────────────────────────────────────────────────────

export interface FlowStep {
  description: string;
  file: string;
  line_range: string; // e.g., "24-35"
  concepts: string[];
}

export interface UserFlow {
  name: string;
  trigger: string;
  steps: FlowStep[];
  difficulty: DifficultyLevel;
}

// ─── File Analysis ──────────────────────────────────────────────────

export interface FileConnections {
  imports_from: string[];
  imported_by: string[];
  data_flow: string;
}

export interface FileAnalysis {
  path: string;
  role: string;
  complexity: number; // 1-5
  difficulty: FileDifficulty;
  key_concepts: string[];
  prerequisites: string[];
  gotchas: string[];
  teaching_notes: string;
  connections: FileConnections;
}

// ─── Architecture ───────────────────────────────────────────────────

export interface ArchitectureLayer {
  name: string;
  description: string;
  files: string[];
  patterns: string[];
}

export interface DesignPattern {
  name: string;
  where_used: string[]; // "file:line" format
  why_used: string;
  teaching_level: DifficultyLevel;
}

export interface Architecture {
  layers: ArchitectureLayer[];
  design_patterns: DesignPattern[];
  data_flow_summary: string; // markdown
}

// ─── Code Quality ───────────────────────────────────────────────────

export interface GoodPractice {
  description: string;
  files: string[];
  concept: string;
}

export interface ImprovementArea {
  description: string;
  severity: QualityInsightSeverity;
  files: string[];
  teaching_opportunity: string;
}

export interface SecurityNote {
  observation: string;
  files: string[];
  teaching_concept: string;
}

export interface CodeQuality {
  good_practices: GoodPractice[];
  improvement_areas: ImprovementArea[];
  security_notes: SecurityNote[];
}

// ─── Learning Priorities ────────────────────────────────────────────

export interface LevelPriority {
  start_with: string[];
  focus_on: string[];
}

export interface BeginnerPriority extends LevelPriority {
  skip_for_now: string[];
}

export interface IntermediatePriority extends LevelPriority {
  deep_dive: string[];
}

export interface AdvancedPriority extends LevelPriority {
  challenge_topics: string[];
}

export interface LearningPriorities {
  beginner: BeginnerPriority;
  intermediate: IntermediatePriority;
  advanced: AdvancedPriority;
}

// ─── Repeated Patterns ──────────────────────────────────────────────

export interface PatternOccurrence {
  file: string;
  line_range: string;
}

export interface RepeatedPattern {
  name: string;
  description: string;
  occurrences: PatternOccurrence[];
  teaching_value: string;
}

// ─── Root Type ──────────────────────────────────────────────────────

export interface EducationalAnalysis {
  project_overview: ProjectOverview;
  user_flows: UserFlow[];
  file_analysis: FileAnalysis[];
  architecture: Architecture;
  code_quality: CodeQuality;
  learning_priorities: LearningPriorities;
  repeated_patterns: RepeatedPattern[];
}
