import type { Metadata } from "next";
import Link from "next/link";
import { BookOpen, Clock, GraduationCap, Layers } from "lucide-react";
import { getPublicLearningPaths } from "@/server/actions/public-learning";
import { getLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "Learn | VibeUniv",
  description:
    "AI가 분석한 실제 프로젝트 기반 학습 커리큘럼을 무료로 미리보기. 바이브 코딩으로 만든 앱의 기술 스택을 이해해보세요.",
  openGraph: {
    title: "무료 학습 커리큘럼 미리보기 | VibeUniv",
    description: "AI가 실제 프로젝트를 분석해서 만든 맞춤 학습 콘텐츠를 지금 바로 확인하세요.",
  },
};

const difficultyColors: Record<string, string> = {
  beginner: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  intermediate: "bg-amber-500/15 text-amber-400 border-amber-500/30",
  advanced: "bg-rose-500/15 text-rose-400 border-rose-500/30",
};

export default async function PublicLearnPage() {
  const paths = await getPublicLearningPaths();
  const locale = await getLocale();
  const isKo = locale === "ko";

  return (
    <div className="max-w-[960px] mx-auto px-8 max-md:px-4 py-12">
      {/* Hero */}
      <div className="text-center mb-12">
        <div className="inline-flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-4 py-1.5 mb-6">
          <GraduationCap className="h-4 w-4 text-violet-400" />
          <span className="text-xs font-medium text-violet-400">
            {isKo ? "무료 미리보기" : "Free Preview"}
          </span>
        </div>
        <h1 className="text-3xl md:text-4xl font-bold text-text-primary mb-4">
          {isKo ? "AI가 만든 맞춤 학습 커리큘럼" : "AI-Generated Custom Learning Curriculum"}
        </h1>
        <p className="text-text-muted max-w-xl mx-auto leading-relaxed">
          {isKo
            ? "실제 프로젝트의 코드를 교재로 삼아 AI가 생성한 학습 콘텐츠입니다. 첫 2개 모듈을 무료로 체험해보세요."
            : "Learning content generated by AI using real project code as textbooks. Try the first 2 modules for free."}
        </p>
      </div>

      {/* Path List */}
      {paths.length === 0 ? (
        <div className="text-center py-20 text-text-muted">
          {isKo ? "아직 공개된 커리큘럼이 없습니다." : "No public curricula available yet."}
        </div>
      ) : (
        <div className="space-y-4">
          {paths.map((path) => (
            <Link
              key={path.id}
              href={`/learn/${path.id}`}
              className="block rounded-2xl border border-border-default bg-bg-primary hover:border-violet-500/40 transition-all p-6 group"
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-2">
                    <h2 className="text-lg font-semibold text-text-primary group-hover:text-violet-400 transition-colors truncate">
                      {path.title}
                    </h2>
                    <span
                      className={`shrink-0 rounded-full border px-2.5 py-0.5 text-[10px] font-medium capitalize ${
                        difficultyColors[path.difficulty ?? "beginner"] ?? difficultyColors.beginner
                      }`}
                    >
                      {path.difficulty ?? "beginner"}
                    </span>
                  </div>
                  <p className="text-sm text-text-muted line-clamp-2 mb-3">
                    {path.description}
                  </p>
                  <div className="flex items-center gap-4 text-xs text-text-muted">
                    <span className="flex items-center gap-1">
                      <Layers className="h-3.5 w-3.5" />
                      {path.module_count} {isKo ? "모듈" : "modules"}
                    </span>
                    {path.estimated_hours && (
                      <span className="flex items-center gap-1">
                        <Clock className="h-3.5 w-3.5" />
                        {path.estimated_hours}h
                      </span>
                    )}
                    {path.project_name && (
                      <span className="flex items-center gap-1">
                        <BookOpen className="h-3.5 w-3.5" />
                        {path.project_name}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>
      )}

      {/* CTA */}
      <div className="mt-16 text-center rounded-2xl border border-violet-500/20 bg-gradient-to-br from-violet-500/5 to-cyan-500/5 p-8">
        <h3 className="text-xl font-bold text-text-primary mb-2">
          {isKo ? "나만의 맞춤 커리큘럼을 만들어보세요" : "Create Your Own Custom Curriculum"}
        </h3>
        <p className="text-sm text-text-muted mb-6 max-w-md mx-auto">
          {isKo
            ? "여러분의 프로젝트를 연결하면 AI가 기술 스택을 분석하고, 내 코드를 교재로 삼아 학습 로드맵을 만들어줍니다."
            : "Connect your project and AI analyzes your tech stack, creating a learning roadmap using your code as the textbook."}
        </p>
        <Link
          href="/signup"
          className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-br from-violet-500 to-cyan-500 px-6 py-3 text-sm font-semibold text-white hover:opacity-90 transition-opacity"
        >
          {isKo ? "무료로 시작하기" : "Get Started Free"}
        </Link>
      </div>
    </div>
  );
}
