/**
 * Template Selection Logic with 3-Level Fallback Cascade.
 *
 * Level 1: Exact Match (concept_key + difficulty + locale)
 * Level 2: Difficulty Relaxation (same concept, different difficulty)
 * Level 3: LLM Fallback placeholder (marks sections needing generation)
 *
 * Design doc: Section 2.4
 */

import { createClient } from "@supabase/supabase-js";
import type { ContentSection } from "@/server/actions/curriculum";
import type { Locale } from "@/types/database";
import { SECTION_TYPE_WEIGHTS } from "./constants";
import {
  getMinSections,
  getMinExplanationChars,
  getMinCodeExamples,
  getMinQuizQuestions,
} from "@/lib/utils/curriculum-validation";

// ─── Types ──────────────────────────────────────────────────────────

export interface SelectionResult {
  sections: ContentSection[];
  /** Number of sections that need LLM fallback (Level 3) */
  llmFallbackCount: number;
  /** True if all sections are pre-built (no LLM needed) */
  fullyPrebuilt: boolean;
}

interface TemplateRow {
  id: string;
  section_type: string;
  difficulty: string;
  title: string;
  body: string;
  code: string | null;
  quiz_options: string[] | null;
  quiz_answer: number | null;
  quiz_explanation: string | null;
}

// ─── Service Client (untyped — content_templates not in Database type) ─

function createTemplateClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    throw new Error("Supabase environment variables are not configured");
  }
  return createClient(url, serviceKey);
}

// ─── Helpers ────────────────────────────────────────────────────────

/** Convert a DB template row to a ContentSection */
function rowToSection(row: TemplateRow): ContentSection {
  const section: ContentSection = {
    type: row.section_type,
    title: row.title,
    body: row.body,
  };

  if (row.code != null) section.code = row.code;
  if (row.quiz_options != null) section.quiz_options = row.quiz_options;
  if (row.quiz_answer != null) section.quiz_answer = row.quiz_answer;
  if (row.quiz_explanation != null) section.quiz_explanation = row.quiz_explanation;

  return section;
}

type SectionType = "explanation" | "code_example" | "quiz_question" | "reflection";

/**
 * Determine the required section counts for a module based on
 * module_type and difficulty.
 */
function getRequiredSectionCounts(
  moduleType: string,
  difficulty: string,
): { explanation: number; code_example: number; quiz_question: number; reflection: number; total: number } {
  const weights = SECTION_TYPE_WEIGHTS[moduleType] ?? SECTION_TYPE_WEIGHTS.concept;
  const minTotal = getMinSections(difficulty);
  const minCode = getMinCodeExamples(difficulty);
  const minQuiz = getMinQuizQuestions(difficulty);

  // Scale weights to approximate counts (round to nearest integer)
  const weightSum = weights.explanation + weights.code_example + weights.quiz_question + weights.reflection;
  const scale = weightSum > 0 ? minTotal / weightSum : 1;

  let explanation = Math.max(1, Math.round(weights.explanation * scale));
  let code_example = Math.max(minCode, Math.round(weights.code_example * scale));
  let quiz_question = Math.max(minQuiz, Math.round(weights.quiz_question * scale));
  const reflection = Math.max(0, Math.round(weights.reflection * scale));

  // Ensure curriculum-validation minimums
  code_example = Math.max(code_example, minCode);
  quiz_question = Math.max(quiz_question, minQuiz);
  if (difficulty === "beginner") {
    explanation = Math.max(explanation, 2);
  }

  const total = Math.max(minTotal, explanation + code_example + quiz_question + reflection);
  return { explanation, code_example, quiz_question, reflection, total };
}

/**
 * Check if a template row's body length meets the minimum for its section type.
 */
function meetsBodyLengthRequirement(row: TemplateRow, difficulty: string): boolean {
  if (row.section_type === "explanation") {
    return row.body.trim().length >= getMinExplanationChars(difficulty);
  }
  return row.body.trim().length >= 20;
}

/**
 * Create a placeholder ContentSection for LLM fallback.
 * Signals that this section needs to be generated by LLM.
 */
function createLlmFallbackPlaceholder(
  sectionType: SectionType,
  conceptKey: string,
): ContentSection {
  const section: ContentSection = {
    type: sectionType,
    title: `[LLM_FALLBACK] ${conceptKey} - ${sectionType}`,
    body: `__LLM_FALLBACK__:${conceptKey}:${sectionType}`,
  };

  if (sectionType === "code_example") {
    section.code = "__LLM_FALLBACK__";
  }
  if (sectionType === "quiz_question") {
    section.quiz_options = ["__A__", "__B__", "__C__", "__D__"];
    section.quiz_answer = 0;
    section.quiz_explanation = "__LLM_FALLBACK__";
  }

  return section;
}

// ─── Gap Detection ──────────────────────────────────────────────────

interface Gap {
  sectionType: string;
  count: number;
}

function findGaps(
  selectedByType: Map<string, ContentSection[]>,
  required: { explanation: number; code_example: number; quiz_question: number; reflection: number },
): Gap[] {
  const gaps: Gap[] = [];
  const typeReqs: Array<[string, number]> = [
    ["explanation", required.explanation],
    ["code_example", required.code_example],
    ["quiz_question", required.quiz_question],
    ["reflection", required.reflection],
  ];

  for (const [sectionType, requiredCount] of typeReqs) {
    if (requiredCount <= 0) continue;
    const current = (selectedByType.get(sectionType) ?? []).length;
    if (current < requiredCount) {
      gaps.push({ sectionType, count: requiredCount - current });
    }
  }

  return gaps;
}

// ─── Result Builder ─────────────────────────────────────────────────

function buildResult(
  selectedByType: Map<string, ContentSection[]>,
  required: { explanation: number; code_example: number; quiz_question: number; reflection: number; total: number },
  llmFallbackCount: number,
): SelectionResult {
  const sectionOrder: SectionType[] = ["explanation", "code_example", "quiz_question", "reflection"];
  const sections: ContentSection[] = [];

  for (const sectionType of sectionOrder) {
    const typeSections = selectedByType.get(sectionType) ?? [];
    const requiredCount = required[sectionType];
    sections.push(...typeSections.slice(0, Math.max(requiredCount, 0)));
  }

  // If total sections < minimum, add more from available templates
  while (sections.length < required.total) {
    let added = false;
    for (const sectionType of sectionOrder) {
      const typeSections = selectedByType.get(sectionType) ?? [];
      const alreadyIncluded = sections.filter((s) => s.type === sectionType).length;
      if (alreadyIncluded < typeSections.length) {
        sections.push(typeSections[alreadyIncluded]);
        added = true;
        break;
      }
    }
    if (!added) break;
  }

  return {
    sections,
    llmFallbackCount,
    fullyPrebuilt: llmFallbackCount === 0,
  };
}

function buildFullFallback(
  conceptKeys: string[],
  required: { explanation: number; code_example: number; quiz_question: number; reflection: number; total: number },
): SelectionResult {
  const sections: ContentSection[] = [];
  let fallbackCount = 0;

  const typeReqs: Array<[SectionType, number]> = [
    ["explanation", required.explanation],
    ["code_example", required.code_example],
    ["quiz_question", required.quiz_question],
    ["reflection", required.reflection],
  ];

  for (const [sectionType, count] of typeReqs) {
    for (let i = 0; i < count; i++) {
      const conceptKey = conceptKeys[i % conceptKeys.length];
      sections.push(createLlmFallbackPlaceholder(sectionType, conceptKey));
      fallbackCount++;
    }
  }

  return { sections, llmFallbackCount: fallbackCount, fullyPrebuilt: false };
}

// ─── Main Function ──────────────────────────────────────────────────

/**
 * Select pre-built template sections for a module from content_templates DB.
 *
 * Uses a 3-Level Fallback Cascade:
 * - Level 1: Exact match (concept_key + difficulty + locale)
 * - Level 2: Difficulty relaxation (same concept, different difficulty, body length check)
 * - Level 3: LLM fallback placeholder (marks sections needing generation)
 */
export async function selectTemplatesForModule(
  conceptKeys: string[],
  difficulty: string,
  locale: Locale,
  moduleType: string,
): Promise<SelectionResult> {
  if (conceptKeys.length === 0) {
    return { sections: [], llmFallbackCount: 0, fullyPrebuilt: false };
  }

  const supabase = createTemplateClient();
  const required = getRequiredSectionCounts(moduleType, difficulty);

  // ─── Level 1: Exact Match ─────────────────────────────────────────

  const { data: exactRows, error: exactError } = await supabase
    .from("content_templates")
    .select("id, section_type, difficulty, title, body, code, quiz_options, quiz_answer, quiz_explanation")
    .in("concept_key", conceptKeys)
    .eq("difficulty", difficulty)
    .eq("locale", locale)
    .order("concept_key")
    .order("section_type");

  if (exactError) {
    console.error("[template-selector] Level 1 query error:", exactError.message);
    return buildFullFallback(conceptKeys, required);
  }

  const exactTemplates = (exactRows ?? []) as TemplateRow[];

  const selectedByType = new Map<string, ContentSection[]>();
  const usedTitles = new Set<string>();

  for (const row of exactTemplates) {
    const titleLower = row.title.trim().toLowerCase();
    if (usedTitles.has(titleLower)) continue;
    if (!meetsBodyLengthRequirement(row, difficulty)) continue;

    const existing = selectedByType.get(row.section_type) ?? [];
    existing.push(rowToSection(row));
    selectedByType.set(row.section_type, existing);
    usedTitles.add(titleLower);
  }

  const gaps = findGaps(selectedByType, required);
  if (gaps.length === 0) {
    return buildResult(selectedByType, required, 0);
  }

  // ─── Level 2: Difficulty Relaxation ───────────────────────────────

  const gapTypes = [...new Set(gaps.map((g) => g.sectionType))];

  const { data: relaxedRows, error: relaxedError } = await supabase
    .from("content_templates")
    .select("id, section_type, difficulty, title, body, code, quiz_options, quiz_answer, quiz_explanation")
    .in("concept_key", conceptKeys)
    .in("section_type", gapTypes)
    .eq("locale", locale)
    .neq("difficulty", difficulty)
    .order("difficulty");

  if (relaxedError) {
    console.error("[template-selector] Level 2 query error:", relaxedError.message);
  }

  const relaxedTemplates = (relaxedRows ?? []) as TemplateRow[];

  // Sort by difficulty preference
  const diffPriority = (d: string): number => {
    if (d === difficulty) return 0;
    if (d === "intermediate") return 1;
    return 2;
  };
  relaxedTemplates.sort((a, b) => diffPriority(a.difficulty) - diffPriority(b.difficulty));

  for (const row of relaxedTemplates) {
    const titleLower = row.title.trim().toLowerCase();
    if (usedTitles.has(titleLower)) continue;
    if (!meetsBodyLengthRequirement(row, difficulty)) continue;

    const existing = selectedByType.get(row.section_type) ?? [];
    existing.push(rowToSection(row));
    selectedByType.set(row.section_type, existing);
    usedTitles.add(titleLower);
  }

  const remainingGaps = findGaps(selectedByType, required);
  if (remainingGaps.length === 0) {
    return buildResult(selectedByType, required, 0);
  }

  // ─── Level 3: LLM Fallback Placeholder ────────────────────────────

  let llmFallbackCount = 0;

  for (const gap of remainingGaps) {
    const existing = selectedByType.get(gap.sectionType) ?? [];
    for (let i = 0; i < gap.count; i++) {
      const conceptKey = conceptKeys[i % conceptKeys.length];
      existing.push(createLlmFallbackPlaceholder(gap.sectionType as SectionType, conceptKey));
      llmFallbackCount++;
    }
    selectedByType.set(gap.sectionType, existing);
  }

  return buildResult(selectedByType, required, llmFallbackCount);
}

// ─── Coverage Check ─────────────────────────────────────────────────

/**
 * Check template coverage for multiple technologies against their KB concepts.
 */
export async function checkMultiTechCoverage(
  techConcepts: Array<{ techName: string; conceptKeys: string[] }>,
  locale: Locale,
): Promise<{
  overall: "full" | "partial" | "none";
  perTech: Array<{
    techName: string;
    level: "full" | "partial" | "none";
    covered: number;
    total: number;
  }>;
}> {
  const allConceptKeys = techConcepts.flatMap((tc) => tc.conceptKeys);

  if (allConceptKeys.length === 0) {
    return {
      overall: "none",
      perTech: techConcepts.map((tc) => ({
        techName: tc.techName,
        level: "none" as const,
        covered: 0,
        total: tc.conceptKeys.length,
      })),
    };
  }

  const supabase = createTemplateClient();

  const { data, error } = await supabase
    .from("content_templates")
    .select("concept_key, technology_name")
    .in("concept_key", allConceptKeys)
    .eq("locale", locale);

  if (error || !data) {
    return {
      overall: "none",
      perTech: techConcepts.map((tc) => ({
        techName: tc.techName,
        level: "none" as const,
        covered: 0,
        total: tc.conceptKeys.length,
      })),
    };
  }

  const coveredKeys = new Set<string>();
  for (const row of data) {
    coveredKeys.add(row.concept_key as string);
  }

  const perTech = techConcepts.map((tc) => {
    const covered = tc.conceptKeys.filter((k) => coveredKeys.has(k)).length;
    const total = tc.conceptKeys.length;
    let level: "full" | "partial" | "none" = "none";
    if (covered === total && total > 0) level = "full";
    else if (covered > 0) level = "partial";
    return { techName: tc.techName, level, covered, total };
  });

  const allFull = perTech.every((t) => t.level === "full");
  const anyPresent = perTech.some((t) => t.level !== "none");
  const overall = allFull ? "full" : anyPresent ? "partial" : "none";

  return { overall, perTech };
}
